# Build settings
gems:
  - jekyll-redirect-from
  - jemoji
  - jekyll-paginate

permalink: /:categories/:title

# Site settings
title: "Talha Zekeriya Durmuş"
description: > # this means to ignore newlines until "email:"
   Bir bilgisayar sevdalısı, Ankara Üniversiteli ve genç bir hayalperest.

email: drtzack@gmail.com
#blog logo
logo: "/assets/images/author.jpg"
# blog cover
cover: "/assets/images/cover.jpg"

name: 'Talha Zekeriya Durmuş'
author: 'Talha Zekeriya Durmuş'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://talhadurmus.com" # the base hostname & protocol for your site
enforce_ssl: talhadurmus.com
baseurl: ""
#used to display twitter cards
twitter_handle: '@drtzack'

#fill in disqus shortname to use disqus
disqus: talhadurmus

# social icons and sharing options
social:
#  - icon:	twitter
#    url:	https://twitter.com/drtzack
#    desc: Beni twitter'dan takip edin
#    share_url: http://twitter.com/share
#    share_title: asdasd?text=
#    share_link: "asdas&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/zek
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
